fix: "yarn types:generate", .env obsolete URLs, formatting/linting/types
The `.env` file had obsolete URLs in it, copied the currently used
values from the test environment into it.

Type generation (i.e. "yarn types:generate") failed because of:
```
Error: Cannot use GraphQLInputObjectType "ApproveOrderMutationInput"
from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of
other relied on modules, use "resolutions" to ensure only one version is
installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since
different versions may have different capabilities and behavior. The
data from one version used in the function from another could produce
confusing and spurious results.
```

Just removing `graphql` from dependencies fixed the above issue with
"yarn types:generate", as `graphql` package comes as a dependency
through other packages.

Add "yarn typecheck" command to check types in pre-push command, as the
"yarn build" command will anyway check types and will fail if
"yarn typecheck" doesn't pass.

Fix broken data (i.e. did not conform to the types) used in tests by
adding the missing fields, removing unused fields etc and updating
snapshots.

Also:
 - Fix linting (i.e. "yarn lint --fix")
 - Fix SCSS style linting (i.e. "yarn stylelint --fix")
 - Update generated types (i.e. "yarn types:generate")
 - Ignore import/order newlines-between linting
   - This setting is for an unknown reason broken i.e. it does not work
     similarly between local development environment and CI/CD pipeline.
     If one uses "yarn lint --fix" locally it will format the code in
     such a way that "yarn lint" will fail when run in CI/CD pipeline.
     I looked into this a bit, but couldn't find the cause. As the VAT
     percentage change has a hard deadline in less than two weeks,
     I feel it is acceptable to ignore this linting setting in order to
     be able to use the allotted time towards more fruitful pursuits,
     instead of fighting with flummoxing lint issues.

refs VEN-1575 (groundwork to be able to make VAT percentage change)